version: "3.8"

services:
  mongodb:
    image: "mongo"
    volumes:
      - data:/data/db

  backend:
    build:
      context: ./backend/src
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - logs:/app/logs
    depends_on:
      - mongodb

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - frontend_src:/app/src
    depends_on:
      - backend

volumes:
  data:
  logs:
  frontend_src:
